# apiVersion: v1
# kind: Secret
# metadata:
#   name: argocd-met
#   namespace: argocd
#   labels:
#     argocd.argoproj.io/secret-type: repository
# stringData:
#   url: git@github.com:MedDDhia/exercice_helm.git
#   sshPrivateKey: |
#     -----BEGIN OPENSSH PRIVATE KEY-----
#     b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
#     QyNTUxOQAAACD+OgkZ2tadRkuOtX5WZzdz3W+FSdx4JahvgHrlp43U4wAAAJjY7EHW2OxB
#     1gAAAAtzc2gtZWQyNTUxOQAAACD+OgkZ2tadRkuOtX5WZzdz3W+FSdx4JahvgHrlp43U4w
#     AAAEAIQ5R0FrdLXR5pc5RbaxsCyQo7Pc7DOaBvGtcY34ldd/46CRna1p1GS461flZnN3Pd
#     b4VJ3HglqG+AeuWnjdTjAAAAE21lZGRoaWE1NEBnbWFpbC5jb20BAg==
#     -----END OPENSSH PRIVATE KEY-----

#   insecure: "false"
#   enableLfs: "true"